name: uxplay
base: core24
adopt-info: uxplay
license: GPL-3.0
summary: AirPlay-Mirror and AirPlay-Audio server
description: |
  **NOTE:** X11 is not supported by this snap.

  UxPlay is a AirPlay Unix mirroring server.

  It lets you mirror your iPhone, iPad or Mac desktop screen to your desktop, where it appears in a floating window that can be shared with other apps, like Discord and OBS Studio.

  UxPlay is a screen mirror only. You can't interact with what you see on the screen.

  This snap is not affiliated with the upstream project in any way. If you encounter any issues, please kindly report it here.

grade: stable
confinement: strict

platforms:
  amd64:
  arm64:

apps:
  uxplay:
    extensions: [ gnome ]
    plugs: [ audio-playback, avahi-control, network, network-bind, opengl, wayland ]
    # daemon: simple
    # daemon-scope: user
    environment:
      GST_PLUGIN_PATH: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/gstreamer-1.0
      LD_LIBRARY_PATH: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/blas:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/lapack:$LD_LIBRARY_PATH
    command: usr/bin/uxplay

parts:
  uxplay:
    plugin: cmake
    source: https://github.com/FDH2/UxPlay.git
    source-type: git
    source-tag: 'v1.72.1'
    source-depth: 1
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DNO_X11_DEPS=ON
      - -DNO_MARCH_NATIVE=ON
    override-pull: |
      craftctl default
      craftctl set version=$(git describe --abbrev=0 --tags | tr -d 'v')
    build-packages:
      # - cmake
      # - ninja-build
      # - build-essential
      # - dpkg-dev
      - libssl-dev
      - libplist-dev
      - libavahi-compat-libdnssd-dev
      - libgstreamer1.0-dev
      - libgstreamer-plugins-base1.0-dev
    stage-packages:
      - libavahi-compat-libdnssd1
      - libplist-2.0-4
      - gstreamer1.0-plugins-base
      - gstreamer1.0-plugins-good
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-gl
      - gstreamer1.0-libav
      - gstreamer1.0-pipewire
      - gstreamer1.0-tools
      - gstreamer1.0-vaapi
    prime:
      - -usr/share/doc
      - -usr/share/icons
      - -usr/share/locale
